name: Fetch Fuel Prices Daily

on:
  schedule:
    - cron: '30 8 * * *'  # Runs daily at 6:00 UTC (adjust if needed)
  workflow_dispatch:     # Allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SCOPE: ${{ secrets.SCOPE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pandas schedule

      - name: Run the script
        run: python FetchPricesNL.py

      - name: Commit output
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output.csv
          git commit -m "Update output.csv [auto]" || echo "No changes"
          git push
